### ISSUE TITLE
Arabica doesn't build with xerces versions lower than v3.x.x

### ISSUE THREAD

**Issue by sBouzols** [jezhiggins/arabica#22]
In the objective to make an intern C++ XML Parsing benchmark, I'm using Arabica as a candidate with xerces expat an libxml2. We actually use an old version of xerces (2.7.0), so i need to compare to this.

I found that Arabica doesn't build with xerces libs versions like 2.7.0 or 2.8.0 mainly because of XMLFilePos and XMLSize_t missing definitions, which is auto-managed in xerces versions greater than 3.0.0.

Adding this part of code in saxxerces.hpp seems to fix it, but maybe it's a little easy and I didn't test a lot.

in (...)/include/SAX/wrappers/saxxerces.hpp:
```cpp
...
namespace Arabica
{
namespace SAX
{

#ifndef XERCES_AUTOCONF
typedef unsigned int XMLFilePos; 
typedef unsigned int XMLSize_t;
#endif

...
```

Are you ok to fix modern versions of Arabica to build with old xerces library versions ?

Thanks

**Comment by jezhiggins** [comment]
Yes I'd be happy to accept a change along these lines, but I'd strongly prefer the ifdef/ifndef condition to use _XERCES_VERSION or one of the other version macros. Have a look in xercesc/util/XercesVersion.hpp - there are a number you could use.

Please feel free to raise a PR.
